theme               = "cocoa"
baseurl             = "http://pages.kenryooo.net/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "ja-JP"
layoutdir           = "layouts"
publishdir          = "public"
author              = "kenryooo"
title               = "kenryooo.net blog"
pygmentsuseclasses  = true
disqusshortname     = "kenryooo-pages.disqus.com" # Comment out to disable Disqus.
pluralizelisttitles = false
googleAnalytics     = "UA-89732412-1"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author       = "kenryooo"
cachebuster  = true # add the current unix timestamp in query string for cache busting css assets
dateform     = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description  = "Python, Golang, AWS, GCP, Hugo などのメモがメインのブログです。"
faviconfile  = "img/leaf.ico"
github       = "//github.com/kenryooo"
highlightjs  = true
lang         = "ja"
twitter      = "//twitter.com/kenryooo"

# gravatar             = ""     # do not use in the same time as avatar
# avatar               = ""     # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# highlightjslanguages = ["go"] # additional languages not included in the "common" set

extracssfiles = [ "/css/override.css" ] # In your `static` directory, add/remove files as necessary.

# The following are DEPRECATED.
# gatracker              = "XYZ" # use googleAnalytics instead
# initials               = "ad"  # displayed on single post page; deprecated in v0.3.0.
